name: Test, Release Tag, Update Changelog
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version: 1.19
      - name: Start containers
        run: docker-compose -f "infra/docker-compose.yaml" up -d
      - run: go test ./...
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: ./version.json
          release-count: 0
      - name: Stop containers
        if: always()
        run: docker-compose -f "infra/docker-compose.yaml" down